import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Download App | Bid 4 Me',
  description: 'Generated by create next app',
}


export default function DownloadPage() {
  return (
    <div>
      DownloadPage
    </div>
  )
}
