import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'FlashSale | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function FlashSalePage() {
  return (
    <div>
      FlashSalePage
    </div>
  )
}
