import { Authentication } from '@/assets/images'
import { LoginForm } from '@/components'
import type { Metadata } from 'next'
import Image from 'next/image'
import styles from './login.module.css'

export const metadata: Metadata = {
  title: 'Login | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function LoginPage() {
  return (
    <main>
      <section className={styles.section}>
        <div className={styles.content}>
          <div className={styles.rightContent}>
            <Image src={Authentication} alt="auth" />
          </div>
          <div className={styles.leftContent}>
            <LoginForm />
          </div>
        </div>
      </section>
    </main>
  )
}
