import { LoginForm } from '@/components'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Login | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function LoginPage() {
  return (
    <main>
      login page
      <LoginForm />
    </main>
  )
}
