import type { Metadata } from 'next'
import { HeroSwiper } from '@/components'

export const metadata: Metadata = {
  title: 'Bid 4 Me',
  description: 'Generated by create next app',
}

export default function HomePage() {
  return (
    <main>

      <section className='lg:h-[500px] hero grid grid-cols-3 gap-4'>
        <div className='border border-red-500 h-full col-span-3 lg:col-span-2'>
          <HeroSwiper />
        </div>
        <div className='h-full col-span-3 lg:col-span-1'>
          <div className='h-full grid grid-cols-2 lg:grid-cols-none grid-rows-none lg:grid-rows-2 gap-4'>
            <div className='border border-red-500 bg-secondary-300 col-span-2 md:col-span-1 lg:row-span-1'>dsds</div>
            <div className='border border-red-500 bg-primary-300 col-span-2 md:col-span-1 lg:row-span-1'>dsdsd</div>
          </div>
        </div>
      </section>

      <section>

      </section>

      <section>

      </section>
    </main>
  )
}
