import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sign Up | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function SignUpPage() {
  return (
    <div>

    </div>
  )
}
