import type { Metadata } from 'next'
import { Authentication } from '@/assets/images'
import { SignupForm } from '@/components'
import Image from 'next/image'
import styles from '@/styles/authform.module.css'

export const metadata: Metadata = {
  title: 'Signup | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function SignUpPage() {
  return (
    <main>
      <section className={styles.section}>
        <div className={styles.content}>
          <div className={styles.rightContent}>
            <Image src={Authentication} alt="auth" priority />
          </div>
          <div className={styles.leftContent}>
            <SignupForm />
          </div>
        </div>
      </section>
    </main>
  )
}
