import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Become a Seller | Bid 4 Me',
  description: 'Generated by create next app',
}


export default function BecomeASellerPage() {
  return (
    <div>
      BecomeASellerPage
    </div>
  )
}
