import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cart Lists | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function CartPage() {
  return (
    <div>
      CartPage
    </div>
  )
}
