import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Auction | Bid 4 Me',
  description: 'Generated by create next app',
}


export default function AuctionPage() {
  return (
    <div>
      AuctionPage
    </div>
  )
}
