import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Raffle | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function RafflePage() {
  return (
    <main>
      RafflePage
    </main>
  )
}
