import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Bid 4 Me',
  description: 'Generated by create next app',
}

export default function HomePage() {
  return (
    <></>
  )
}
