import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Notifications | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function NotificationPage() {
  return (
    <div>

    </div>
  )
}
