import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Installment | Bid 4 Me',
  description: 'Generated by create next app',
}


export default function InstallmentPage() {
  return (
    <div>
      InstallmentPage
    </div>
  )
}
