import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'FreeShipping | Bid 4 Me',
  description: 'Generated by create next app',
}

export default function FreeShippingPage() {
  return (
    <div>
      FreeShippingPage
    </div>
  )
}
